# Numpy

np.array(리스트) : 리스트 데이터를 넘파이 배열로 바꾸어 생성

In [5]:
import numpy as np

num_list = [1,2,3,4]
int_arr2 = np.array(num_list)
print(int_arr2)

[1,2,3,4]

[1 2 3 4]


[1, 2, 3, 4]

In [6]:
np.__version__

'2.3.3'

np.arrange(시작 인덱스 : 끝 인덱스 : 간격)

넘파이 배열에 들어가는 자료형

- 한가지 데이터 타입으로 통일되어 처리된다. (한가지 데이터 타입만 들어가짐)

넘파이 배열 생성
- 2차원 배열 생성 : 행렬(matrix) / 가로줄은 행(row), 세로줄은 열(column)
- 3차원 배열 생성 : 텐서(tensor)
#
#

 - 몇 차원인지 확인할 수 있는 : 넘파이 배열명.ndim
 - 몇 행, 몇 열인지 확인할 수 있는 : 넘파이 배열명.shape
 - 배열의 차원을 변경할 수 있는 : 넘파이 배열명.reshape(크기)
  - ex) arr2 = arr.reshape(2,5) : 2열 5행짜리 배열로 바꾸겠다.
  - 괄호 안의 인수 중에 하나 넣고, 나머지에 -1을 넣으면 그 모양에 맞춰서 배열 만들어 줌

  #
  - shape이 같다면 사칙연산을 알아서 할 수 있음

In [7]:
L = range(1000)
%timeit L2 = [i ** 2 for i in L] #매진응용어?

47.3 μs ± 2.97 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [8]:
arr = np.arange(1000)
%timeit arr2 = arr**2


1.16 μs ± 46 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [10]:
alist = [1,2,3,4,5,6]

In [11]:
blist = [1,2, None, 4, 5, 6]

In [12]:
ar1 = np.array(alist)
print(ar1)
print(type(ar1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [14]:
ar1.dtype

dtype('int64')

In [15]:
ar2 = np.array([1.1, 2.2, 3/3])

In [16]:
ar2.dtype

dtype('float64')

In [18]:
list_data = [1,2,3]

ar3 = np.array(list_data)

print(ar3)
print(ar3.dtype)

[1 2 3]
int64


In [ ]:
np.array([1,2, np.nan ,4]) #nan = not a number / None = 아예 값이 없는 것

array([ 1.,  2., nan,  4.])

In [21]:
arr1 = np.array([1,2,3,4])

print(arr1)
print(arr1.ndim)
print(arr1.shape)

[1 2 3 4]
1
(4,)


In [23]:
arr2 = np.array([[1,2,3,4]])

print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[1 2 3 4]]
2
(1, 4)


In [24]:
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) 

print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)


In [32]:
arr3 = arr2.reshape(2, -1, 3)

In [30]:
print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)


In [37]:
alist = np.array([1,2,3,4,5])
blist = np.array([6,7,8,9,np.nan])

In [38]:
print(alist + blist)
print(alist - blist)
print(alist * blist)
print(alist / blist)

[ 7.  9. 11. 13. nan]
[-5. -5. -5. -5. nan]
[ 6. 14. 24. 36. nan]
[0.16666667 0.28571429 0.375      0.44444444        nan]


In [43]:
a = np.array([1,2,3])
b = np.array([10,20,30])

print (2 * a + b)

print(a == 2)
print(b > 10)
print((a == 2) & (b>10))

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


## 인덱스, 슬라이싱
- 인덱스 0부터 시작 . 음수 인덱싱 지원 O ([-1] 이 맨 끝자리) _ List와 동일


In [52]:
alist = [(0,1,2), [3,4,5]]
print (alist [0][0])
print (alist [0][1])
print (alist [1][-1])

0
1
5


In [72]:
alist = [[0, 1, 2],[3,4,5]]

print(alist[0][:2])
print(alist[1][1:])

[0, 1]
[4, 5]


In [74]:
result = [alist[0][1], alist[1][1]]
result

[1, 4]

In [75]:
blist = np.array([[0,1,2],[3,4,5]])
blist

array([[0, 1, 2],
       [3, 4, 5]])

In [76]:
print(blist[0][0], blist[0][1], blist[1][2])

0 1 5


In [78]:
blist[,]

SyntaxError: invalid syntax (3075824922.py, line 1)

In [79]:
blist[0,:2]

array([0, 1])

In [82]:
blist[-1, 1:]

array([4, 5])

In [ ]:
a = np.array([[0,1,2,3],[4,5,6,7]])

print(a[:,:2])

print(a[0:2,0:2])  #[행자리, 열자리]


[[0 1]
 [4 5]]
[[0 1]
 [4 5]]


In [114]:
clist = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])

print(clist[1:3, 1:3])
print()
print(clist[1,:2])
print()
print(clist[1:4,1:4])
print()
print(clist[:, -2:-1])

[[ 5  6]
 [ 9 10]]

[4 5]

[[ 5  6  7]
 [ 9 10 11]]

[[ 2]
 [ 6]
 [10]]


In [116]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = [0,2,5]
a[idx]

array([0, 2, 5])

In [117]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
b[[0,2]] #0행, 2행 불러올래

array([[1, 2, 3],
       [7, 8, 9]])

In [120]:
b[[0,1,2],[1,2,0]]

array([2, 6, 7])

In [121]:
arr = np.array([1,2,3,4,5,6,7,8])

In [122]:
arr % 2 == 0

array([False,  True, False,  True, False,  True, False,  True])

In [123]:
arr[arr%2 ==0]

array([2, 4, 6, 8])

In [124]:
clist [:,-2]

array([ 2,  6, 10])

In [125]:
clist[:,-2:-1]

array([[ 2],
       [ 6],
       [10]])

In [126]:
a = np.array([0,1,2,3,4,5,6,7,8,9])

a[a%2==1]

array([1, 3, 5, 7, 9])

In [128]:
a = np.array([11,22,33,44,55,66,77,88,99])
idx = np.array([0,2,4,6,8])
a[idx]

array([11, 33, 55, 77, 99])

In [129]:
a = np.array([11,22,33,44,55,66,77,88,99])
idx = np.array([0,0,0,0,0,0,1,1,1,1,1,2,2,2,2,2])
a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

### Fancy indexing 

In [142]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [139]:
a[:,[True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [141]:
a[:,[0,3]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [143]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [144]:
a[[2,0,1], :]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [145]:
import numpy as np

In [ ]:
data = np.array([1,4,9,16])

In [150]:
np.sqrt(data)

array([1., 2., 3., 4.])

In [151]:
np.exp(data)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06])

In [152]:
np.sum(data)

np.int64(30)

In [153]:
np.std(data)

np.float64(5.678908345800274)

In [154]:
np.sum(data)

np.int64(30)

In [155]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

x[x%3==0]

array([ 3,  6,  9, 12, 15, 18])

In [156]:
x[x%4==1]

array([ 1,  5,  9, 13, 17])

In [165]:
x[(x%3==0)&(x%4==1)]

array([9])

In [166]:
!pip install pandas

   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
    --------------------------------------- 0.2/11.3 MB 4.6 MB/s eta 0:00:03
   --- ------------------------------------ 0.9/11.3 MB 9.5 MB/s eta 0:00:02
   ------ --------------------------------- 1.8/11.3 MB 13.0 MB/s eta 0:00:01
   ----------- ---------------------------- 3.1/11.3 MB 16.7 MB/s eta 0:00:01
   ---------------- ----------------------- 4.6/11.3 MB 19.6 MB/s eta 0:00:01
   ---------------------- ----------------- 6.3/11.3 MB 23.7 MB/s eta 0:00:01
   ---------------------- ----------------- 6.3/11.3 MB 23.7 MB/s eta 0:00:01
   ---------------------- ----------------- 6.3/11.3 MB 23.7 MB/s eta 0:00:01
   ---------------------- ----------------- 6.3/11.3 MB 23.7 MB/s eta 0:00:01
   --------------------------- ------------ 7.9/11.3 MB 17.5 MB/s eta 0:00:01
   ----------------------------- ---------- 8.4/11.3 MB 17.9 MB/s eta 0:00:01
   ----------------------------- ---------- 8.4/11.3 MB 17.9 MB/s eta 0:00


[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [169]:
import pandas as pd

In [171]:
df = pd.read_csv('heroes.csv')
df

이름  나이     직업     국적    키            재산
0   아이언맨  58    CEO     미국  174  1.150000e+13
1     토르  45      신  아스가르드  190           NaN
2  스파이더맨  18   고등학생     미국  177  6.000000e+02
3   원더우먼  27     공주  데미스키라  178           NaN
4     헐크  33  핵물리학자     미국  270  1.000000e+09
5   캡틴마블  25    파일럿     미국  170  3.400000e+08
6  블랙위도우  32    스파이    러시아  170  5.000000e+07

In [172]:
pd.options.display.float_format = '{:.0f}'.format

In [173]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [174]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


In [ ]:
df.describe()       #이상치(아웃라이어)가 있는지를 min, max 등으로 확인해보기
#수치형 자료들만 보여줌

나이   키             재산
count   7   7              5
mean   34 190  2300278000120
std    13  36  5142800956894
min    18 170            600
25%    26 172       50000000
50%    32 177      340000000
75%    39 184     1000000000
max    58 270 11500000000000

In [ ]:
df.head() # 앞에 있는 데이터 5개 보여줌
#df.head(3) #앞에서 세개
#df.tail() # 뒤에 있는 데이터 5개 보여줌
#괄호 비우면 디폴트값 5개, 숫자 쓰면 해당 숫자만큼

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000

In [177]:
df['국적']

0       미국
1    아스가르드
2       미국
3    데미스키라
4       미국
5       미국
6      러시아
Name: 국적, dtype: object

In [ ]:
type(df['국적']) #1차원데이터 _ 시리즈.

pandas.core.series.Series

In [ ]:
df['국적'].unique() #중복빼고 몇종류인지

array(['미국', '아스가르드', '데미스키라', '러시아'], dtype=object)

In [183]:
df['국적'].value_counts()

국적
미국       4
아스가르드    1
데미스키라    1
러시아      1
Name: count, dtype: int64

In [185]:
df['나이'].nlargest()

0    58
1    45
4    33
6    32
3    27
Name: 나이, dtype: int64

In [ ]:
df.nlargest(7,'나이') #나이 기준 많은 순서부터 해서 7개 정렬

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
6  블랙위도우  32    스파이    러시아  170       50000000
3   원더우먼  27     공주  데미스키라  178            NaN
5   캡틴마블  25    파일럿     미국  170      340000000
2  스파이더맨  18   고등학생     미국  177            600

In [187]:
df.nlargest(7,'키') #키 기준 큰 순서부터 해서 7개 정렬

이름  나이     직업     국적    키             재산
4     헐크  33  핵물리학자     미국  270     1000000000
1     토르  45      신  아스가르드  190            NaN
3   원더우먼  27     공주  데미스키라  178            NaN
2  스파이더맨  18   고등학생     미국  177            600
0   아이언맨  58    CEO     미국  174 11500000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [ ]:
df['이름'] #시리즈 형태로 출력, 슬라이스 가능?

0     아이언맨
1       토르
2    스파이더맨
3     원더우먼
4       헐크
5     캡틴마블
6    블랙위도우
Name: 이름, dtype: object

In [189]:
df['이름'][:5]

0     아이언맨
1       토르
2    스파이더맨
3     원더우먼
4       헐크
Name: 이름, dtype: object

In [193]:
df #전체에서도 슬라이스 가능

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [194]:
df[:3]

이름  나이    직업     국적    키             재산
0   아이언맨  58   CEO     미국  174 11500000000000
1     토르  45     신  아스가르드  190            NaN
2  스파이더맨  18  고등학생     미국  177            600

In [195]:
#df.iloc, df.loc #i는 인덱스 접근 방식, loc는 위치 기반(숫자,이름)

In [ ]:
df.iloc[1:4,0:] #df.iloc[행번호, 열번호]

이름  나이    직업     국적    키  재산
1     토르  45     신  아스가르드  190 NaN
2  스파이더맨  18  고등학생     미국  177 600
3   원더우먼  27    공주  데미스키라  178 NaN

In [ ]:
df.iloc[[1,3,6]]  #1,3,6번째 인덱스 나와봐~

이름  나이   직업     국적    키       재산
1     토르  45    신  아스가르드  190      NaN
3   원더우먼  27   공주  데미스키라  178      NaN
6  블랙위도우  32  스파이    러시아  170 50000000

In [207]:
df.iloc[:5,:3]

이름  나이     직업
0   아이언맨  58    CEO
1     토르  45      신
2  스파이더맨  18   고등학생
3   원더우먼  27     공주
4     헐크  33  핵물리학자

In [209]:
df.loc[0, "이름"]

'아이언맨'

In [ ]:
df.loc[2:5] #마지막 숫자가 포함됨 (글자 기준이라)

이름  나이     직업     국적    키         재산
2  스파이더맨  18   고등학생     미국  177        600
3   원더우먼  27     공주  데미스키라  178        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
5   캡틴마블  25    파일럿     미국  170  340000000

In [213]:
df.loc[:2,['이름','직업']]

이름    직업
0   아이언맨   CEO
1     토르     신
2  스파이더맨  고등학생

In [214]:
df.loc[3: , '국적':'재산']

국적    키         재산
3  데미스키라  178        NaN
4     미국  270 1000000000
5     미국  170  340000000
6    러시아  170   50000000

In [216]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [225]:
df['나이'] > 30

0     True
1     True
2    False
3    False
4     True
5    False
6     True
Name: 나이, dtype: bool

In [226]:
df[df['나이'] < 50]

이름  나이     직업     국적    키         재산
1     토르  45      신  아스가르드  190        NaN
2  스파이더맨  18   고등학생     미국  177        600
3   원더우먼  27     공주  데미스키라  178        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
5   캡틴마블  25    파일럿     미국  170  340000000
6  블랙위도우  32    스파이    러시아  170   50000000

In [224]:
df[(df['나이'] > 30) & (df['나이'] <50)]

이름  나이     직업     국적    키         재산
1     토르  45      신  아스가르드  190        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
6  블랙위도우  32    스파이    러시아  170   50000000

In [229]:
df.loc[df['키'] >=180,['이름','나이','키']]


이름  나이    키
1  토르  45  190
4  헐크  33  270

In [230]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [242]:
df['전투력'] = 98

In [234]:
df

이름  나이     직업     국적    키             재산  전투력
0   아이언맨  58    CEO     미국  174 11500000000000   98
1     토르  45      신  아스가르드  190            NaN   98
2  스파이더맨  18   고등학생     미국  177            600   98
3   원더우먼  27     공주  데미스키라  178            NaN   98
4     헐크  33  핵물리학자     미국  270     1000000000   98
5   캡틴마블  25    파일럿     미국  170      340000000   98
6  블랙위도우  32    스파이    러시아  170       50000000   98

In [235]:
df['전투력'] = df['전투력'] - 5

In [236]:
df

이름  나이     직업     국적    키             재산  전투력
0   아이언맨  58    CEO     미국  174 11500000000000   93
1     토르  45      신  아스가르드  190            NaN   93
2  스파이더맨  18   고등학생     미국  177            600   93
3   원더우먼  27     공주  데미스키라  178            NaN   93
4     헐크  33  핵물리학자     미국  270     1000000000   93
5   캡틴마블  25    파일럿     미국  170      340000000   93
6  블랙위도우  32    스파이    러시아  170       50000000   93

In [244]:
#컬럼을 삭제하는 방법 #drop (일단 임시로 삭제해보기)
df.drop(columns =['전투력'])

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [240]:
#컬럼을 삭제하는 방법 #drop #inplace = True 는 진짜 삭제하겠다는 뜻
df.drop(columns =['전투력'], inplace = True) 

In [245]:
df = df.drop(columns =['전투력'])

In [246]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000

In [247]:
#결측치 삭제
#일단 어디 결측치가 있는지 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


In [248]:
#재산에 결측치 있음을 확인함.

In [ ]:
df['재산'] 

0   11500000000000
1              NaN
2              600
3              NaN
4       1000000000
5        340000000
6         50000000
Name: 재산, dtype: float64

In [250]:
df['재산'].isnull() #이라고 물어봐서 True면 결측치

0    False
1     True
2    False
3     True
4    False
5    False
6    False
Name: 재산, dtype: bool

In [251]:
df[df['재산'].isnull()]

이름  나이  직업     국적    키  재산
1    토르  45   신  아스가르드  190 NaN
3  원더우먼  27  공주  데미스키라  178 NaN

In [ ]:
df.isnull().sum() #어디에 결측치 몇개있나 확인

이름    0
나이    0
직업    0
국적    0
키     0
재산    2
dtype: int64

In [253]:
df.dropna() #결측치 제거

이름  나이     직업   국적    키             재산
0   아이언맨  58    CEO   미국  174 11500000000000
2  스파이더맨  18   고등학생   미국  177            600
4     헐크  33  핵물리학자   미국  270     1000000000
5   캡틴마블  25    파일럿   미국  170      340000000
6  블랙위도우  32    스파이  러시아  170       50000000

In [254]:
#재산이 없는 사람들이 없어지게 됐어요 와우

In [255]:
df

이름  나이     직업     국적    키             재산
0   아이언맨  58    CEO     미국  174 11500000000000
1     토르  45      신  아스가르드  190            NaN
2  스파이더맨  18   고등학생     미국  177            600
3   원더우먼  27     공주  데미스키라  178            NaN
4     헐크  33  핵물리학자     미국  270     1000000000
5   캡틴마블  25    파일럿     미국  170      340000000
6  블랙위도우  32    스파이    러시아  170       50000000